name: nurseconnect_shared
description: A shared package for NurseConnect data models and utilities.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2 # Ensure this matches your Flutter project's SDK

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies required by your shared models
  equatable: ^2.0.7 # If your models extend Equatable
  cloud_firestore: ^5.6.6 # If models have fromJson/toJson using Firestore conventions
  dartz: ^0.10.1 # For functional programming constructs like Either
  google_fonts: ^6.1.0
  # Add any other dependencies your shared models need
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  freezed: ^2.5.2
  build_runner: ^2.5.4
  json_serializable: ^6.8.0