name: nurseconnect_patient
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.0 # Use the latest version found on pub.dev if needed

  # Service Locator / Dependency Injection
  get_it: ^8.0.3 # Use the latest version

  # HTTP Client
  # dio: ^5.8.0+1 # Use the latest version

  # Value equality helper (often used with Bloc states)
  equatable: ^2.0.7

  # Functional Programming helpers (for Either, etc.)
  dartz: ^0.10.1


  # --- Firebase ---
  firebase_core: ^3.15.1 # Check latest
  firebase_auth: ^5.5.2 # Check latest
  firebase_messaging: ^15.2.5 # Add this line (check pub.dev for latest version)
  cloud_firestore: ^5.6.6 # Check latest
  firebase_storage: ^12.4.9 # Check latest
  firebase_app_check: ^0.3.2+5
  firebase_crashlytics: ^4.0.2
  cloud_functions: ^5.6.1

  intl: ^0.19.0
  # --- End Firebase ---

  # Add go_router: (Check pub.dev for the absolute latest version)
  go_router: ^15.0.0 # Example: Use the latest stable version

  # Add geolocator for location services
  geolocator: ^14.0.2
  google_maps_flutter: ^2.5.3
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0

  nurseconnect_shared:
    path: ../nurseconnect_shared
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0 # Add for BLoC testing
  build_runner: ^2.5.4 # Add build_runner

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package