name: nurseconnect_admin
description: Admin dashboard for the NurseConnect ecosystem.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  cloud_functions: ^5.6.1
  intl: ^0.19.0
  provider: ^6.0.0
  google_maps_flutter: ^2.5.3
  csv: ^5.0.1
  universal_html: ^2.2.4

  # Path to your shared library
  nurseconnect_shared:
    path: ../nurseconnect_shared
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true